-- AlterTable
ALTER TABLE "Matchup" ADD COLUMN     "myProjPoints" DOUBLE PRECISION,
ADD COLUMN     "myStartersProjPoints" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "opponentProjPoints" DOUBLE PRECISION,
ADD COLUMN     "opponentStartersProjPoints" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[];
