// Curated player list — tier + rank. Order is the master rank (top to
// bottom, all positions mixed); posRank is derived from position within
// that order. Editable by hand, but the intended way to change it is the
// owner-only tier board at /admin (components/TierBoard.tsx), which
// overwrites this file on save. See CLAUDE.md.

export type PlayerTuple = [name: string, pos: string, team: string, tier: number, posRank: number];

export const RAW: PlayerTuple[] = [
  ["Ja'Marr Chase","WR","CIN",1,1],
  ["Bijan Robinson","RB","ATL",1,1],
  ["CeeDee Lamb","WR","DAL",1,2],
  ["Saquon Barkley","RB","PHI",1,2],
  ["Jahmyr Gibbs","RB","DET",1,3],
  ["Justin Jefferson","WR","MIN",1,3],
  ["Amon-Ra St. Brown","WR","DET",1,4],
  ["Christian McCaffrey","RB","SF",1,4],
  ["Josh Allen","QB","BUF",1,1],
  ["Lamar Jackson","QB","BAL",1,2],
  ["Jayden Daniels","QB","WAS",1,3],
  ["Malik Nabers","WR","NYG",2,5],
  ["De'Von Achane","RB","MIA",2,5],
  ["Nico Collins","WR","HOU",2,6],
  ["Ashton Jeanty","RB","LV",2,6],
  ["Brian Thomas Jr.","WR","JAX",2,7],
  ["Derrick Henry","RB","BAL",2,7],
  ["Drake London","WR","ATL",2,8],
  ["A.J. Brown","WR","PHI",2,9],
  ["Josh Jacobs","RB","GB",2,8],
  ["Jonathan Taylor","RB","IND",2,9],
  ["Brock Bowers","TE","LV",2,1],
  ["Jalen Hurts","QB","PHI",2,4],
  ["Joe Burrow","QB","CIN",2,5],
  ["Patrick Mahomes","QB","KC",2,6],
  ["Puka Nacua","WR","LAR",2,10],
  ["Bucky Irving","RB","TB",3,10],
  ["Ladd McConkey","WR","LAC",3,11],
  ["Kyren Williams","RB","LAR",3,11],
  ["Tee Higgins","WR","CIN",3,12],
  ["Chase Brown","RB","CIN",3,12],
  ["Garrett Wilson","WR","NYJ",3,13],
  ["Marvin Harrison Jr.","WR","ARI",3,14],
  ["Jaxon Smith-Njigba","WR","SEA",3,15],
  ["Kenneth Walker III","RB","SEA",3,13],
  ["Davante Adams","WR","LAR",3,16],
  ["Terry McLaurin","WR","WAS",3,17],
  ["Trey McBride","TE","ARI",3,2],
  ["George Kittle","TE","SF",3,3],
  ["James Cook","RB","BUF",3,14],
  ["Baker Mayfield","QB","TB",3,7],
  ["Bo Nix","QB","DEN",3,8],
  ["Kyler Murray","QB","ARI",3,9],
  ["Brock Purdy","QB","SF",3,10],
  ["Caleb Williams","QB","CHI",3,11],
  ["Jordan Love","QB","GB",3,12],
  ["Justin Herbert","QB","LAC",3,13],
  ["Tyreek Hill","WR","MIA",3,18],
  ["Mike Evans","WR","TB",4,19],
  ["DK Metcalf","WR","PIT",4,20],
  ["DJ Moore","WR","CHI",4,21],
  ["Breece Hall","RB","NYJ",4,15],
  ["Alvin Kamara","RB","NO",4,16],
  ["Chuba Hubbard","RB","CAR",4,17],
  ["Aaron Jones","RB","MIN",4,18],
  ["Joe Mixon","RB","HOU",4,19],
  ["David Montgomery","RB","DET",4,20],
  ["Tony Pollard","RB","TEN",4,21],
  ["Jaylen Waddle","WR","MIA",4,22],
  ["Chris Olave","WR","NO",4,23],
  ["Zay Flowers","WR","BAL",4,24],
  ["Courtland Sutton","WR","DEN",4,25],
  ["Jordan Addison","WR","MIN",4,26],
  ["Jerry Jeudy","WR","CLE",4,27],
  ["Xavier Worthy","WR","KC",4,28],
  ["Jameson Williams","WR","DET",4,29],
  ["Sam LaPorta","TE","DET",4,4],
  ["DeVonta Smith","WR","PHI",4,30],
  ["Omarion Hampton","RB","LAC",4,22],
  ["Dak Prescott","QB","DAL",4,14],
  ["Trevor Lawrence","QB","JAX",4,15],
  ["Drake Maye","QB","NE",4,16],
  ["C.J. Stroud","QB","HOU",4,17],
  ["Tua Tagovailoa","QB","MIA",4,18],
  ["Rhamondre Stevenson","RB","NE",5,23],
  ["Zamir White","RB","LV",5,24],
  ["Najee Harris","RB","LAC",5,25],
  ["Amari Cooper","WR","BUF",5,31],
  ["Rome Odunze","WR","CHI",5,32],
  ["Keon Coleman","WR","BUF",5,33],
  ["Calvin Ridley","WR","TEN",5,34],
  ["Stefon Diggs","WR","NE",5,35],
  ["Cooper Kupp","WR","SEA",5,36],
  ["Deebo Samuel","WR","WAS",5,37],
  ["Mark Andrews","TE","BAL",5,5],
  ["Travis Kelce","TE","KC",5,6],
  ["T.J. Hockenson","TE","MIN",5,7],
  ["David Njoku","TE","CLE",5,8],
  ["Dalton Kincaid","TE","BUF",5,9],
  ["Jayden Reed","WR","GB",5,38],
  ["Khalil Shakir","WR","BUF",5,39],
  ["Jakobi Meyers","WR","LV",5,40],
  ["Brian Robinson Jr.","RB","WAS",5,26],
  ["Isiah Pacheco","RB","KC",5,27],
  ["Travis Etienne Jr.","RB","JAX",5,28],
  ["D'Andre Swift","RB","CHI",5,29],
  ["Rachaad White","RB","TB",5,30],
  ["Travis Hunter","WR","JAX",5,41],
  ["Tetairoa McMillan","WR","CAR",5,42],
  ["TreVeyon Henderson","RB","NE",5,31],
  ["Quinshon Judkins","RB","CLE",5,32],
  ["Kaleb Johnson","RB","PIT",5,33],
  ["Fernando Mendoza","QB","LV",5,19],
  ["Cam Ward","QB","TEN",5,20],
  ["Anthony Richardson","QB","IND",5,21],
  ["Michael Penix Jr.","QB","ATL",5,22],
  ["Dallas Goedert","TE","PHI",6,10],
  ["Jonnu Smith","TE","MIA",6,11],
  ["Evan Engram","TE","DEN",6,12],
  ["Jauan Jennings","WR","SF",6,43],
  ["Tank Bigsby","RB","JAX",6,34],
  ["Tyrone Tracy Jr.","RB","NYG",6,35],
  ["Jaylen Warren","RB","PIT",6,36],
  ["Javonte Williams","RB","DAL",6,37],
  ["Jordan Mason","RB","MIN",6,38],
  ["Ricky Pearsall","WR","SF",6,44],
  ["Jayden Higgins","WR","HOU",6,45],
  ["Matthew Golden","WR","GB",6,46],
  ["RJ Harvey","RB","DEN",6,39],
];
